Repository PLUS-POSTECH/Owl, pull requests merged in 2018-08, with the labels that each got.

#17 Update database schema, move out owl-rpc
  Cargo.toml
  owl-cli/Cargo.toml
  owl-cli/src/main.rs
  owl-daemon/Cargo.toml
  owl-daemon/migrations/2018-07-23-061204_initialize_tables/down.sql
  owl-daemon/migrations/2018-07-23-061204_initialize_tables/up.sql
  owl-daemon/src/db/models.rs
  owl-daemon/src/db/schema.rs
  owl-daemon/src/lib.rs
  owl-daemon/src/main.rs
  owl-exploit/Cargo.toml
  owl-exploit/src/lib.rs
  owl-exploit/src/tests.rs
  owl-rpc/Cargo.toml
  owl-rpc/src/lib.rs
Labels: design, new feature, refactoring

#26 Feature/team service register
  owl-cli/Cargo.toml
  owl-cli/src/error.rs
  owl-cli/src/main.rs
  owl-cli/src/service/mod.rs
  owl-cli/src/team.rs
  owl-daemon/src/db/mod.rs
  owl-daemon/src/db/models.rs
  owl-daemon/src/error.rs
  owl-daemon/src/handler/mod.rs
  owl-daemon/src/handler/service/mod.rs
  owl-daemon/src/handler/team.rs
  owl-daemon/src/lib.rs
  owl-daemon/src/main.rs
  owl-rpc/Cargo.toml
  owl-rpc/src/error.rs
  owl-rpc/src/lib.rs
  owl-rpc/src/model/service/mod.rs
  owl-rpc/src/model/team.rs
Labels: new feature

#29 Implement service provider, service variant related action
  owl-cli/src/error.rs
  owl-cli/src/main.rs
  owl-cli/src/service/mod.rs
  owl-cli/src/service/provider.rs
  owl-cli/src/service/variant.rs
  owl-daemon/Cargo.toml
  owl-daemon/src/db/models.rs
  owl-daemon/src/handler/service/mod.rs
  owl-daemon/src/handler/service/provider.rs
  owl-daemon/src/handler/service/variant.rs
  owl-daemon/src/lib.rs
  owl-rpc/src/lib.rs
  owl-rpc/src/model/service/provider.rs
  owl-rpc/src/model/service/variant.rs
Labels: new feature

#30 Features/config parsing
  owl-cli/Cargo.toml
  owl-cli/src/error.rs
  owl-cli/src/main.rs
  owl-cli/src/service/mod.rs
  owl-cli/src/service/provider.rs
  owl-cli/src/service/variant.rs
  owl-cli/src/team.rs
  owl-daemon/Cargo.toml
  owl-daemon/src/db/mod.rs
  owl-daemon/src/error.rs
  owl-daemon/src/handler/service/mod.rs
  owl-daemon/src/handler/service/provider.rs
  owl-daemon/src/handler/service/variant.rs
  owl-daemon/src/handler/team.rs
  owl-daemon/src/lib.rs
  owl-daemon/src/main.rs
  owl-rpc/Cargo.toml
Labels: new feature

#31 Features/impl exploit
  owl-cli/src/error.rs
  owl-cli/src/exploit.rs
  owl-cli/src/main.rs
  owl-cli/src/service/provider.rs
  owl-cli/src/service/variant.rs
  owl-daemon/migrations/2018-07-23-061204_initialize_tables/up.sql
  owl-daemon/src/db/models.rs
  owl-daemon/src/db/schema.rs
  owl-daemon/src/error.rs
  owl-daemon/src/handler/exploit.rs
  owl-daemon/src/handler/mod.rs
  owl-daemon/src/handler/service/provider.rs
  owl-daemon/src/handler/service/variant.rs
  owl-daemon/src/lib.rs
  owl-rpc/src/lib.rs
  owl-rpc/src/model/exploit.rs
Labels: new feature

#39 Features/run exploit
  owl-cli/src/exploit.rs
  owl-daemon/migrations/2018-07-23-061204_initialize_tables/up.sql
  owl-daemon/src/db/models.rs
  owl-daemon/src/db/schema.rs
  owl-daemon/src/exploit.rs
  owl-daemon/src/handler/exploit.rs
  owl-daemon/src/handler/service/provider.rs
  owl-daemon/src/lib.rs
  owl-rpc/src/model/exploit.rs
  test_scenario/123-0
  test_scenario/123-1
  test_scenario/auth.py
  test_scenario/config.toml
  test_scenario/exploit.py
  test_scenario/run.bat
  test_scenario/test_command
Labels: new feature

#41 Features/alpha quickfix
  owl-cli/Cargo.toml
  owl-cli/src/exploit.rs
  owl-daemon/src/handler/exploit.rs
  owl-daemon/src/handler/service/variant.rs
  owl-daemon/src/lib.rs
  owl-rpc/src/lib.rs
  owl-rpc/src/model/exploit.rs
Labels: bug

#50 Implement exploit timeout
  owl-daemon/src/error.rs
  owl-daemon/src/exploit.rs
  owl-daemon/src/handler/exploit.rs
Labels: new feature
